options
{
  LOOKAHEAD=3;
}
PARSER_BEGIN(ScalrParser)
import java.io.*;

public class ScalrParser {
    public static void main(String[] args) {
		BufferedReader br = null;
        String text = "";
        try {
			br = new BufferedReader(new FileReader(args[0]));
            String line = "";
            while ((line = br.readLine()) != null) {
                text += line + "\n";

            }
            new ScalrParser(new java.io.StringReader(text)).fscalr();
	    System.out.println("grats, your program compiled alright");
        } catch (Throwable e) {
            // Catching Throwable is ugly but JavaCC throws Error objects!
            System.out.println("Syntax check failed: " + e.getMessage());
        }
    }
}
PARSER_END(ScalrParser)

SKIP : { " " | "\t" | <"/*" (~[])* "*/"> | "\n"}
TOKEN: {
       "and" | "or" | "not" | "->" | "." | /*"\n" |*/
        "," | "+" | "-" | "%" | "(" | ")" | "[" | "]" |
	"note" | "pitch" | "volume" | 
       	"duration" | "quarter" | "half" | "whole" |
	"end" | "func" | "while" | "foreach" |
	 "in" |	"if" | "else" | "import" | "track" |
	/*<NL: ("\n")+>|*/ 
	<ASSIGN: "=" | "+=" | "-=" | "*=" | "/=" | "%="> |
	<RELN: "==" | "<" | ">" | ">=" "<="> |
	<INT: "0" | ["1"-"9"](["0"-"9"])*> |
	<ID: ["a"-"z"](["A"-"Z"] | ["a"-"z"] | <INT> | "_")*> |
    	<DEGREE: ["A"-"G"]("b" | "s")?(["0"-"9"] | "1""0")>
	}

//void tscalr(): {} { imports() ("\n")+ function() ("\n")+ (track)+ }

void fscalr(): {} { function() (fscalr2())* }

void fscalr2(): {} { /*("\n")+*/ function() }

void function(): {} {
"func" <ID> "(" (parameters())? ")" fblock() {System.out.println("function matched");}
}

void parameters(): {System.out.println("trying to match parameters:");} { 
<ID> (parameters1())* {System.out.println("Parameters matched");}
}

void parameters1(): {} { "," parameters() }

void fblock(): {System.out.println("matching function block:");} {
(line())* sequence() "end" {System.out.println("fblock matched");}
}

void block(): {System.out.println("matching block:");} { 
(line())+ "end" {System.out.println("block matched");}
}

void line(): {System.out.println("matching line:");} {
loop() {System.out.println("loop line matched");}
| conditional() {System.out.println("conditional line matched");}
| assignment() {System.out.println("assignment line matched");}
}

void loop(): {System.out.println("matching loop");} {
"while" "(" booleanExpr() ")" block()
| "foreach" "(" <ID> "in" sequence() ")" block()
}

void booleanExpr(): {System.out.println("matching bool expr:");} {
bE1() (booleanExpr1())*
}

void booleanExpr1(): {} {
"and" bE1()
| "or" bE1()
}

void bE1(): {Token op; System.out.println("matching bE1:");} {
"not" booleanExpr()
| "(" booleanExpr() ")"
| expression() op=<RELN> expression() {System.out.println(op + " comparison matched");}
}

void conditional (): {System.out.println("matching conditional:");} {
"if" "(" booleanExpr() ")" (line())+ els3()
| "if" "(" booleanExpr() ")" block()
}

void els3(): {System.out.println("matching else");} {
"else" conditional() 
| "else" block()
}

void assignment(): {Token op; System.out.println("matching assignment:");} {
<ID> op=<ASSIGN> expression() {System.out.println(op + " assignment matched");}
}

void expression(): {System.out.println("matching expr");} {
expr1() (expr0())*
| {System.out.println("expression error");}
}

void expr0(): {} {
"+" expr1()
| "-" expr1()
}

void expr1(): {} { expr3() (expr2())* }

void expr2(): {} {
"*" expr3()
| "/" expr3()
}

void expr3(): {} {expr5() (expr4())*}

void expr4(): {} {"%" expr5()}

void expr5(): {} {
"(" expression() ")" 
| operand()
}

void operand(): {Token t; System.out.println("matching operand:");} {
t=<ID> {System.out.println("operand is id "+t);}
| note() {System.out.println("operand is note");}
| sequence() {System.out.println("operand is sequence");}
| t=<INT> {System.out.println("operand is int "+t);} 
}

void note(): {Token n; System.out.println("matching note");} {
"note" (note1())+ {System.out.println("note is created here");}
| sequence() "[" expression() "]" {System.out.println("note is nth in a sequence");}
| n=<ID> {System.out.println("note \"" + n + "\" is an ID");}
}

void note1(): {} {
"." "pitch" "(" ( <DEGREE> | "+" expr5() | "-" expr5() | note() | expression()) ")"
| "." "volume" "(" ("+" expr5() | "-" expr5() | expression()) ")"
| "." "duration" "(" ("+" expr5() | "-" expr5() | expression()) ")"
| "." ("quarter" | "half" | "whole")
}

void sequence(): {Token s; System.out.println("matching sequence:");} {
"[" (note() (sequence1())*)? "]" {System.out.println("Sequence is created here");}
| s=<ID> {System.out.println("Sequence \"" + s + "\" corresponds to an ID");}
}

void sequence1(): {} {"," /*("\n")**/ note()}

void track(): {} {
"track" "->" sequence()
}