/* Generated By:JavaCC: Do not edit this line. ScalrParser2Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScalrParser2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASSIGN = 37;
  /** RegularExpression Id. */
  int RELN = 38;
  /** RegularExpression Id. */
  int INT = 39;
  /** RegularExpression Id. */
  int ID = 40;
  /** RegularExpression Id. */
  int DEGREE = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "\"\\n\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"->\"",
    "\".\"",
    "\",\"",
    "\"\\\"\"",
    "\"+\"",
    "\"-\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"note\"",
    "\"pitch\"",
    "\"volume\"",
    "\"duration\"",
    "\"quarter\"",
    "\"half\"",
    "\"whole\"",
    "\"end\"",
    "\"func\"",
    "\"main\"",
    "\"while\"",
    "\"foreach\"",
    "\"in\"",
    "\"if\"",
    "\"else\"",
    "\"import\"",
    "\"track\"",
    "\".fscalr\"",
    "<ASSIGN>",
    "<RELN>",
    "<INT>",
    "<ID>",
    "<DEGREE>",
    "\"*\"",
    "\"/\"",
  };

}
