#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
# Run the compiler
java -jar $DIR/ScalrParser.jar $1 > tempscalr.scalrlog
# Get the last line
midistring=`tail -n1 tempscalr.scalrlog`
# Remove the temporary
rm tempscalr.scalrlog
if echo $midistring | grep -Eq '^\[.*\]$'
then
	python $DIR/../python-midi-generator/midi_generator.py $midistring
fi
