/* Generated By:JavaCC: Do not edit this line. ScalrParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScalrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int INT = 36;
  /** RegularExpression Id. */
  int ID = 37;
  /** RegularExpression Id. */
  int DEGREE = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"->\"",
    "\".\"",
    "\"\\n\"",
    "\"\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"note\"",
    "\"pitch\"",
    "\"volume\"",
    "\"duration\"",
    "\"end\"",
    "\"func\"",
    "\"while\"",
    "\"foreach\"",
    "\"in\"",
    "\"if\"",
    "\"else\"",
    "\"track\"",
    "<LETTER>",
    "<INT>",
    "<ID>",
    "<DEGREE>",
    "\"=\"",
    "\"+=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"*\"",
    "\"/\"",
  };

}
